on: push
name: Build et déploiement du site
jobs:
  build:
    name: Build et déploiement
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: jzweifel/gatsby-cli-github-action@master
        name: Build Gatsby
        with:
          gatsby-arg: build
      - uses: sebastianpopp/ftp-action@releases/v2
        name: Envoi sur le FTP
        with:
          host: '${{ secrets.FTP_SERVER }}'
          user: '${{ secrets.FTP_USERNAME }}'
          password: '${{ secrets.FTP_PASSWORD }}'
          localDir: public
          remoteDir: www
          options: '--delete --asci'
