on: push
name: Build et déploiement du site
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
	  - uses: actions/checkout@master

	  - uses: actions/cache@master
		name: Cache gatsby build
		env:
		  cache-name: cache-gatsby-build
		with:
		  path: ./public
		  key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
		  restore-keys: |
			${{ runner.os }}-build-${{ env.cache-name }}-
			${{ runner.os }}-build-
			${{ runner.os }}-

	  - name: Build Gatsby
		uses: jzweifel/gatsby-cli-github-action@master
		with:
		  gatsby-arg: build

  deploy:
    name: Déploiement
    runs-on: ubuntu-latest
    needs: build
    steps:
	  - uses: actions/checkout@master

	  - uses: actions/cache@master
		name: Cache gatsby build
		env:
		  cache-name: cache-gatsby-build
		with:
		  path: ./public
		  key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
		  restore-keys: |
			${{ runner.os }}-build-${{ env.cache-name }}-
			${{ runner.os }}-build-
			${{ runner.os }}-

	  - uses: sebastianpopp/ftp-action@releases/v2
		name: Envoi sur le FTP
		with:
		  host: ${{ secrets.FTP_SERVER }}
		  user: ${{ secrets.FTP_USERNAME }}
		  password: ${{ secrets.FTP_PASSWORD }}
		  localDir: "public"
		  remoteDir: "www"
		  options: "--delete --asci"
